### ISSUE TITLE
RAbbit MQ new gpg key

### ISSUE THREAD

**Issue by olimaz** [KETSE/casebox-vagrant#3]
The provision failed because the gpg key changed.  Here is the announce:

http://www.rabbitmq.com/news.html

I managed to correct this with the following command: (taken from https://www.rabbitmq.com/signatures.html)

apt-key adv --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x6B73A36E6026DFCA

**Comment by vmelnic** [comment]
Thank you @olimaz
