### ISSUE TITLE
php-dom not installed

### ISSUE THREAD

**Issue by olimaz** [KETSE/casebox-vagrant#4]
When provisioning the machine, got a Composer error:

[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "
  DOMDocument" from the global namespace.
  Did you forget a "use" statement? in /var/www/casebox-admin/vendor/symfony/symfony/src/Symfony/Component/Confi
  g/Util/XmlUtils.php:52

To fix this, I ssh into the machine (vagrant ssh) and installed it manually:
sudo aptitude install php7.0-dom

**Comment by vmelnic** [comment]
Actually we need to install 'php7.0-xml' instead of 'php7.0-dom'. 
Fixed in provision scripts.
