### ISSUE TITLE
Twig Bundle

### ISSUE THREAD

**Issue by olimaz** [KETSE/casebox-vagrant#5]
When provisioning (composer udpate) got this error:

[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Twig_Error_Runtime]
    The "core" extension is not enabled.

Acording to https://github.com/symfony/symfony/issues/20284  is a version conflict. 

I managed to get over it changing composer.json:
vagrant ssh
nano /var/www/casebox-admin/composer.json
added second  line of the following block:
  "symfony/process": "^3.0",
  **"twig/twig": "^1.0",**
   "twig/extensions": "^1.0",

Finally got it working after "vagrant provision"

**Comment by vmelnic** [comment]
Fixed!
